branches:
  only:
    - feature-theme-devops
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
script:
- yarn deploy:build
cache: yarn
deploy:
  provider: npm
  email: 1063218918@qq.com
  api_key: $NPM_TOKEN
  on:
    branch: feature-theme-devops
  skip-cleanup: true